# Generated by Django 4.2.6 on 2023-11-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='createddate')),
                ('updateddate', models.DateTimeField(auto_now=True, db_column='updateddate')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Strategy',
            },
        ),
    ]
